# Generated by Django 3.0.6 on 2021-05-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='is_vegetarian',
            new_name='is_wegetarian',
        ),
    ]
