# Generated by Django 3.0.6 on 2021-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0002_auto_20210531_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('American', 'American'), ('Italian', 'Italian'), ('Polish', 'Polish'), ('Japanese', 'Japanese')], max_length=256),
        ),
    ]
